baseURL = "/"
languageCode = "en-us"
title = "Coding Ricky"
theme = "hugo-cactus-theme"
googleAnalytics = "UA-47428520-1"

[params]
	name = "Coding Ricky"
	description = "A blog documenting Ricky Yim's software adventures."
	bio = "A blog documenting Ricky Yim's software adventures."
	twitter = "http://twitter.com/codingricky"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "A blog documenting Ricky Yim's software adventures."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/codingricky"
    github   = "https://www.github.com/codingricky"